<a href="https://colab.research.google.com/github/Aakash50909/Machine-Learning-UML501/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(np.flip(arr))

[5 4 3 2 1]


In [8]:
array1=np.array([[1,2,3],[2,4,5],[1,2,3]])
print(np.ndarray.flatten(array1))
print(np.ravel(array1))

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


In [9]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])
print(arr1==arr2)

[[ True  True]
 [ True  True]]


In [17]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])
counts = np.bincount(x)
print(np.argmax(counts))
print(np.where(x==np.argmax(counts)))
counts = np.bincount(y)
print(np.argmax(counts))
print(np.where(y==np.argmax(counts)))

1
(array([0, 5, 7, 8, 9]),)
1
(array([0, 1, 2]),)


In [23]:
gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')
print(np.sum(gfg))
print(np.sum(gfg,axis=0))
print(np.sum(gfg,axis=1))


45
[[20  9 16]]
[[14]
 [16]
 [15]]


In [36]:
n_array=np.array([[55,25,15],[30,44,2],[11,45,77]])
print(np.sum(np.diag(n_array)))
print(np.linalg.eig(n_array))
print(np.linalg.inv(n_array))
print(np.linalg.det(n_array))

176
EigResult(eigenvalues=array([98.16835147, 28.097044  , 49.73460452]), eigenvectors=array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]]))
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001
